using System;
using ZeroTwin3D.Engine;
using ZeroTwin3D.Lighting;

namespace ZeroTwin3D.Rendering
{
    public enum RenderPass
    {
        Opaque,
        Transparent,
        Wireframe
    }

    /// <summary>
    /// Render command generated by the 3D scene traversal for a drawable mesh instance.
    /// </summary>
    public class RenderCommand
    {
        public string NodeName { get; set; } = string.Empty;
        public Mesh3D Mesh { get; set; } = null!;
        public Mat4 WorldTransform { get; set; }
        public Material3D Material { get; set; } = Material3D.Default;
        public Aabb3D WorldBounds { get; set; }
        public float DistanceToCamera { get; set; }
        public RenderPass Pass { get; set; } = RenderPass.Opaque;
        public bool CastShadow { get; set; } = true;
    }
}
